### ISSUE TITLE
An example of how to run the converter would be amazing

### ISSUE THREAD

**Issue by Neophen** [owenfarrell/wsdl2postman#4]
Hey, a simple example of how to run at least your test script would be really appreciated :)

**Comment by owenfarrell** [comment]
@Neophen I didn't wrap a CLI around the converter, as my hope is that [it will get folded in to Postman](https://github.com/postmanlabs/postman-app-support/issues/208) and get called programatically. But the [simple unit tests](https://github.com/owenfarrell/wsdl2postman/blob/master/test/convert-test.js#L37) illustrate the idea.

All you need is a path to a WSDL and the output is a Postman collection.

**Comment by minoseah629** [comment]
@owenfarrell, i invoke converter.parseFile on my wsdl.  

But I do not see an actual output file.

**Comment by owenfarrell** [comment]
@minoseah629 Could you post a snippet of what you're trying to achieve?

The `parseFile` method [accepts a callback function as a parameter](https://github.com/owenfarrell/wsdl2postman/blob/master/convert.js#L8). That function will receive an object representation of the Postman collection as a parameter [here](https://github.com/owenfarrell/wsdl2postman/blob/master/convert.js#L30).

**Comment by minoseah629** [comment]
It appears to be having a problem at this location when expand function is called, the input parameter is null.  it could be bombing out there since it never gets to the callback you mention. 

Attached is the wsdl im trying to target.

--removed zip


![image](https://user-images.githubusercontent.com/1980068/49164373-fde31c00-f2fc-11e8-865e-f43be9e0a449.png)

**Comment by owenfarrell** [comment]
Interesting.

I can't think of a scenario in which a valid WSDL would have an undefined input. An empty array would be totally valid (e.g. no parameters).

Looking at your WSDL, the one thing I don't see is a definition for your binding (`i0:IAccessionsData`, which I'm guessing is defined in the other document that gets imported).

I wonder if the SOAP client stub library that I'm using supports that kind of import.

**Comment by minoseah629** [comment]
@owenfarrell, i did not realize it was missing. 

I targeted the completed wsdl and it got to the callback.

It successfully imported to Postman. 
![image](https://user-images.githubusercontent.com/1980068/49170070-4accef80-f309-11e8-8e5d-2f491b75f59f.png)
